#ifndef INTERFACECARTEDESORTIENUMERIQUE_H_HEADER_INCLUDED_BF698722
#define INTERFACECARTEDESORTIENUMERIQUE_H_HEADER_INCLUDED_BF698722

//##ModelId=407CF29E0341
class InterfaceCarteDeSortieNumerique
{
  public:
    //##ModelId=407CF2CC03DD
    virtual bool ecrireEtatVoie(char voie, char etat) = 0;

};



#endif /* INTERFACECARTEDESORTIENUMERIQUE_H_HEADER_INCLUDED_BF698722 */
