# Makefile generated by the project manager
#


## core information

PRJ_FILE       = PID0.wpj
PRJ_DIR        = D:/Tornado/PID
PRJ_TYPE       = vxApp
PRJ_OBJS       = essai0.o
BUILD_SPEC     = PENTIUMgnu
TGT_DIR        = $(WIND_BASE)/target




## build-configuration info

ifeq ($(BUILD_SPEC),PENTIUMgnu)
CPU              = PENTIUM
TOOL             = gnu
DEFAULT_RULE     = PID0.out
endif

include $(TGT_DIR)/h/make/defs.project

## build-configuration info

ifeq ($(BUILD_SPEC),PENTIUMgnu)
AR               = ar386
AS               = cc386
CC               = cc386
CFLAGS           = -g -mpentium -ansi -nostdinc -DRW_MULTI_THREAD -D_REENTRANT -fvolatile -nostdlib -fno-builtin -fno-defer-pop -I. -IC:/Tornado/target/h -DCPU=PENTIUM
CFLAGS_AS        = -g -mpentium -ansi -nostdinc -fvolatile -nostdlib -fno-builtin -fno-defer-pop -P -x assembler-with-cpp -I. -IC:/Tornado/target/h -DCPU=PENTIUM
CPP              = cc386 -E -P -xc
LD               = ld386
LDFLAGS          = -X -N
LD_PARTIAL_FLAGS = -X -r
NM               = nm386 -g
OPTION_DEFINE_MACRO = -D
OPTION_INCLUDE_DIR = -I
SIZE             = size386
POST_BUILD_RULE  = 
PRJ_LIBS         = 
endif

# override make definitions only below this line


# override make definitions only above this line
include $(TGT_DIR)/h/make/rules.project



## build-configuration info

ifeq ($(BUILD_SPEC),PENTIUMgnu)
essai0.o:
	$(CC) -g -mpentium -ansi -nostdinc -DRW_MULTI_THREAD -D_REENTRANT -fvolatile -nostdlib -fno-builtin -fno-defer-pop -I. -I$(WIND_BASE)/target/h -DCPU=PENTIUM -c $(PRJ_DIR)/essai0.cpp
endif


## dependencies

essai0.o: $(PRJ_DIR)/essai0.cpp \
	$(PRJ_DIR)/Actionneur.cpp \
	$(PRJ_DIR)/BibliothequeTR/Evenement.cpp \
	$(PRJ_DIR)/BibliothequeTR/HorlogeSynchronisee.h \
	$(PRJ_DIR)/fichier.cpp \
	$(PRJ_DIR)/InterfaceCarteDEntreeAnalogique.h \
	$(PRJ_DIR)/BibliothequeTR/Temps.cpp \
	$(PRJ_DIR)/CarteCIODAS64.cpp \
	$(PRJ_DIR)/CorrecteurTW.h \
	$(PRJ_DIR)/fichier.h \
	$(PRJ_DIR)/InterfaceES/InterfaceCarteDEntreeAnalogique.h \
	$(PRJ_DIR)/CapteurDePosition.cpp \
	$(PRJ_DIR)/CapteurDePosition.h \
	$(PRJ_DIR)/InterfaceCarteDeSortieNumerique.h \
	$(PRJ_DIR)/BibliothequeTR/ChienDeGarde.h \
	$(PRJ_DIR)/BibliothequeTR/Tache.h \
	$(PRJ_DIR)/BibliothequeTR/Evenement.h \
	$(PRJ_DIR)/BibliothequeTR/HorlogeSynchronisee.cpp \
	$(PRJ_DIR)/BibliothequeTR/Tache.cpp \
	$(PRJ_DIR)/CorrecteurSTW.h \
	$(PRJ_DIR)/InterfaceCarteDeSortieAnalogique.h \
	$(PRJ_DIR)/Actionneur.h \
	$(PRJ_DIR)/CorrecteurPID.h \
	$(PRJ_DIR)/CarteCIODAS64.h \
	$(PRJ_DIR)/CarteCIODAC16.cpp \
	$(PRJ_DIR)/BibliothequeTR/TypeProcedure.h \
	$(PRJ_DIR)/InterfaceES/InterfaceCarteDeSortieAnalogique.h \
	$(PRJ_DIR)/InterfaceCarteDEntreeNumerique.h \
	$(PRJ_DIR)/CorrecteurTW.cpp \
	$(PRJ_DIR)/CorrecteurPID.cpp \
	$(PRJ_DIR)/ControleurDAxe.h \
	$(PRJ_DIR)/Correcteur.cpp \
	$(PRJ_DIR)/BibliothequeTR/Temps.h \
	$(PRJ_DIR)/Correcteur.h \
	$(PRJ_DIR)/CorrecteurSTW.cpp \
	$(PRJ_DIR)/BibliothequeTR/ChienDeGarde.cpp \
	$(PRJ_DIR)/CarteCIODAC16.h \
	$(PRJ_DIR)/ControleurDAxe.cpp


## user defined rules

