#ifndef INTERFACECARTEDENTREENUMERIQUE_H_HEADER_INCLUDED_BF698794
#define INTERFACECARTEDENTREENUMERIQUE_H_HEADER_INCLUDED_BF698794

//##ModelId=407CF1450132
class InterfaceCarteDEntreeNumerique
{
  public:
    //##ModelId=407CF16001C7
    virtual char lireEtatVoie(char voie) const = 0;

};



#endif /* INTERFACECARTEDENTREENUMERIQUE_H_HEADER_INCLUDED_BF698794 */
