#ifndef INTERFACECARTEDENTREEANALOGIQUE_H_HEADER_INCLUDED_BF699FBD
#define INTERFACECARTEDENTREEANALOGIQUE_H_HEADER_INCLUDED_BF699FBD

//##ModelId=407CD9560326
class InterfaceCarteDEntreeAnalogique
{
  public:
    //##ModelId=407CD98B00C0
    virtual float adConv(char voie) const = 0;

};



#endif /* INTERFACECARTEDENTREEANALOGIQUE_H_HEADER_INCLUDED_BF699FBD */
