#ifndef INTERFACECARTEDESORTIEANALOGIQUE_H_HEADER_INCLUDED_BF69873E
#define INTERFACECARTEDESORTIEANALOGIQUE_H_HEADER_INCLUDED_BF69873E

//##ModelId=407CF08F00E0
class InterfaceCarteDeSortieAnalogique
{
  public:
    //##ModelId=407CF09C01A7
    virtual bool daConv(char voie, float valeur) = 0;

};



#endif /* INTERFACECARTEDESORTIEANALOGIQUE_H_HEADER_INCLUDED_BF69873E */
